const TAGS = {
  skills: ['BIM','Revit','Lean Construction','S10','Costos','Contrataciones Públicas','Ley 32069','SEACE','MS Project','Primavera P6','Calidad','ISO 9001','Seguridad','Power BI','Excel Avanzado','IA aplicada'],
  learning: ['BIM','Revit','Lean Construction','S10','Costos','Contrataciones Públicas','MS Project','Primavera P6','Calidad','Power BI','IA aplicada','Gestión de proyectos'],
  offers: ['Mentoría','Proveedores','Contactos laborales','Asesoría técnica','Revisión de CV','Apoyo en tesis','Consultoría','Revisión BIM','Experiencia en obra'],
  goals: ['Conseguir trabajo','Buscar socios','Conseguir clientes','Emprender','Consultoría','Investigación','Docencia','Networking','Certificaciones'],
  projects: ['Obras públicas','Edificaciones','Hospitales','Colegios','Carreteras','Puentes','Minería','Industria','Vivienda','Hidráulica']
};

const defaultUser = {
  name:'', city:'', company:'', role:'', specialty:'Gestión de proyectos', experience:0,
  skills:[], learning:[], offers:[], goals:[], projects:[], availability:[]
};

const professionals = [
  {id:1,name:'Luis A. Huamani',initials:'LH',city:'Lima',specialty:'Procura y BIM',company:'Consorcio Pepnet PS',skills:['BIM','Revit','Gestión de proyectos'],learning:['Contrataciones Públicas','Ley 32069'],offers:['Mentoría','Experiencia en obra'],goals:['Networking','Consultoría'],projects:['Colegios','Puentes','Edificaciones'],availability:['Viernes 20:30'],score:96},
  {id:2,name:'Johana Espino',initials:'JE',city:'Marcona',specialty:'Calidad',company:'Sector minero',skills:['Calidad','ISO 9001','Seguridad'],learning:['Power BI','Gestión de proyectos'],offers:['Asesoría técnica','Experiencia en obra'],goals:['Networking','Certificaciones'],projects:['Minería','Industria'],availability:['Viernes 20:30'],score:89},
  {id:3,name:'María Paredes',initials:'MP',city:'Lima',specialty:'Coordinación BIM',company:'BIM Lab Perú',skills:['BIM','Revit','Power BI'],learning:['Contrataciones Públicas','Lean Construction'],offers:['Revisión BIM','Mentoría'],goals:['Consultoría','Buscar socios'],projects:['Hospitales','Edificaciones'],availability:['Miércoles 20:00','Viernes 20:30'],score:94},
  {id:4,name:'Pedro Salazar',initials:'PS',city:'Arequipa',specialty:'Costos y planeamiento',company:'Andes Ingeniería',skills:['S10','Costos','MS Project','Primavera P6'],learning:['BIM','IA aplicada'],offers:['Asesoría técnica','Mentoría'],goals:['Networking','Consultoría'],projects:['Carreteras','Puentes'],availability:['Viernes 20:30'],score:87},
  {id:5,name:'Ana Torres',initials:'AT',city:'Trujillo',specialty:'Residencia de obra',company:'Constructora Norte',skills:['Lean Construction','Seguridad','Gestión de proyectos'],learning:['Calidad','Power BI'],offers:['Experiencia en obra','Proveedores'],goals:['Buscar socios','Networking'],projects:['Colegios','Vivienda'],availability:['Miércoles 20:00','Viernes 20:30'],score:91},
  {id:6,name:'Carlos Ríos',initials:'CR',city:'Piura',specialty:'Supervisión',company:'Ríos Consultores',skills:['Calidad','Contrataciones Públicas','Gestión de proyectos'],learning:['BIM','Lean Construction'],offers:['Contactos laborales','Asesoría técnica'],goals:['Conseguir clientes','Consultoría'],projects:['Obras públicas','Hidráulica'],availability:['Miércoles 20:00'],score:85},
  {id:7,name:'Rosa Mendoza',initials:'RM',city:'Cusco',specialty:'Seguridad y SSOMA',company:'Minera Sur',skills:['Seguridad','ISO 9001','Excel Avanzado'],learning:['Power BI','IA aplicada'],offers:['Mentoría','Asesoría técnica'],goals:['Certificaciones','Networking'],projects:['Minería','Industria'],availability:['Viernes 20:30'],score:82},
  {id:8,name:'Diego Chávez',initials:'DC',city:'Lima',specialty:'Arquitectura y diseño',company:'Estudio Forma',skills:['Revit','BIM','IA aplicada'],learning:['Costos','S10'],offers:['Revisión BIM','Consultoría'],goals:['Buscar socios','Conseguir clientes'],projects:['Edificaciones','Vivienda'],availability:['Miércoles 20:00'],score:90}
];

let opportunities = [
  {id:1,type:'Vacante',title:'Especialista BIM',description:'Proyecto hospitalario busca coordinador BIM con experiencia en Revit y Navisworks.',location:'Lima / Híbrido',author:'María Paredes'},
  {id:2,type:'Proyecto',title:'Socio para consultoría de obras públicas',description:'Se busca profesional con experiencia en costos y contrataciones públicas.',location:'Remoto',author:'Carlos Ríos'},
  {id:3,type:'Evento',title:'Webinar: IA aplicada a la construcción',description:'Sesión gratuita organizada por egresados de la maestría.',location:'Virtual',author:'Comunidad UTP'},
  {id:4,type:'Investigación',title:'Colaborador para tesis sobre Lean Construction',description:'Se requiere apoyo en procesamiento y análisis de casos.',location:'Virtual',author:'Ana Torres'},
  {id:5,type:'Consultoría',title:'Revisión de expediente técnico',description:'Consultoría breve para revisión de metrados y presupuesto de colegio.',location:'Piura',author:'Luis Huamani'}
];

const activities = [
  {icon:'🤝',text:'Luis aceptó tu conexión profesional',time:'Hace 2 h'},
  {icon:'💼',text:'Nueva vacante: Especialista BIM',time:'Hace 5 h'},
  {icon:'🏆',text:'Ganaste 20 puntos por asistir a una mesa',time:'Ayer'},
  {icon:'📅',text:'Tu mesa fue programada para el viernes',time:'Ayer'}
];

const history = [
  {date:'18 JUL 2026',title:'Mesa: Gestión de costos y contratos',participants:['Pedro Salazar','Carlos Ríos','Johana Espino'],connections:2,note:'Intercambio sobre S10 y Ley 32069.'},
  {date:'04 JUL 2026',title:'Mesa: Innovación y transformación digital',participants:['María Paredes','Diego Chávez','Rosa Mendoza'],connections:1,note:'Contacto para revisión de modelo BIM.'},
  {date:'20 JUN 2026',title:'Mesa: Calidad y seguridad en obra',participants:['Johana Espino','Ana Torres'],connections:2,note:'Compartieron formatos de control de calidad.'}
];

const ACCOUNTS_KEY='constructnet_accounts_v2';
const SESSION_KEY='constructnet_session_v2';
let currentEmail=localStorage.getItem(SESSION_KEY)||'';
let state = {route:'dashboard',user:{...defaultUser},connections:[],score:0,selectedOpportunityType:'Todos',profileCompleted:false};

function getAccounts(){try{return JSON.parse(localStorage.getItem(ACCOUNTS_KEY)||'[]')}catch{return []}}
function putAccounts(a){localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(a))}
function loadAccount(email){const a=getAccounts().find(x=>x.email===email);if(!a)return false;currentEmail=email;localStorage.setItem(SESSION_KEY,email);state={route:'dashboard',user:{...defaultUser,...(a.user||{})},connections:a.connections||[],score:Number(a.score||0),selectedOpportunityType:'Todos',profileCompleted:!!a.profileCompleted};return true}
function persistAccount(){if(!currentEmail)return;const accounts=getAccounts();const i=accounts.findIndex(x=>x.email===currentEmail);if(i<0)return;accounts[i]={...accounts[i],user:state.user,connections:state.connections,score:state.score,profileCompleted:state.profileCompleted};putAccounts(accounts)}


const app = document.getElementById('app');
const toast = document.getElementById('toast');

function notify(message){ toast.textContent=message; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),2600); }
function initials(name){return name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function setRoute(route){state.route=route; document.querySelectorAll('.nav-item,.bottom-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route)); render(); document.getElementById('sidebar').classList.remove('open'); window.scrollTo({top:0,behavior:'smooth'});}
function cloneTpl(id){return document.getElementById(id).content.cloneNode(true)}
function saveState(){persistAccount();}
function personCard(p, showConnect=true){return `<article class="person-card"><div class="person-top"><div class="person-avatar">${p.initials}</div><div><h3>${p.name}</h3><p>${p.specialty}</p><small>${p.company} · ${p.city}</small></div></div><div class="tag-list">${p.skills.slice(0,3).map(t=>`<span class="tag">${t}</span>`).join('')}</div><p><strong>Puede aportar:</strong> ${p.offers.slice(0,2).join(', ')}</p><p><strong>Busca:</strong> ${p.learning.slice(0,2).join(', ')}</p>${showConnect?`<div class="person-actions"><button class="secondary-btn" onclick="notify('Perfil de ${p.name} abierto')">Ver perfil</button><button class="primary-btn" onclick="toggleConnection(${p.id})">${state.connections.includes(p.id)?'Conectado':'Conectar'}</button></div>`:''}</article>`}
function opportunityCard(o){return `<article class="op-card"><span class="pill">${o.type}</span><h3>${o.title}</h3><p>${o.description}</p><div class="op-meta"><span>📍 ${o.location}</span><span>👤 ${o.author}</span></div></article>`}
function calculateSynergy(user, person){
  const learningMatch=user.learning.filter(x=>person.skills.includes(x)).length;
  const reverseMatch=person.learning.filter(x=>user.skills.includes(x)).length;
  const goalMatch=user.goals.filter(x=>person.goals.includes(x)).length;
  const projectMatch=user.projects.filter(x=>person.projects.includes(x)).length;
  const availabilityMatch=user.availability.filter(x=>person.availability.includes(x)).length;
  return Math.min(99,55+learningMatch*8+reverseMatch*7+goalMatch*5+projectMatch*4+availabilityMatch*6);
}
function selectRoomMembers(){return [...professionals].map(p=>({...p,calculated:calculateSynergy(state.user,p)})).sort((a,b)=>b.calculated-a.calculated).slice(0,5)}
function toggleConnection(id){state.connections=state.connections.includes(id)?state.connections.filter(x=>x!==id):[...state.connections,id]; if(!state.connections.includes(id)) notify('Conexión eliminada'); else {state.score+=40;notify('¡Nueva conexión profesional! +40 puntos');} saveState(); render();}
window.toggleConnection=toggleConnection; window.notify=notify;

function renderDashboard(){app.replaceChildren(cloneTpl('dashboardTpl')); app.querySelectorAll('[data-user-name]').forEach(e=>e.textContent=(state.user.name||'Estudiante').split(' ')[0]); document.getElementById('topAvatar').textContent=initials(state.user.name||'Estudiante UTP'); document.getElementById('dashConnections').textContent=state.connections.length;document.getElementById('dashScore').textContent=state.score;const members=selectRoomMembers();document.getElementById('dashMembers').innerHTML=members.map(p=>`<span class="mini-avatar" title="${p.name}">${p.initials}</span>`).join('');document.getElementById('activityList').innerHTML=activities.map(a=>`<div class="activity-item"><span class="activity-icon">${a.icon}</span><div><p>${a.text}</p><small>${a.time}</small></div></div>`).join('');document.getElementById('featuredOpportunities').innerHTML=opportunities.slice(0,3).map(opportunityCard).join('');}
function renderProfile(){app.replaceChildren(cloneTpl('profileTpl'));const form=document.getElementById('profileForm');Object.entries(state.user).forEach(([k,v])=>{if(form.elements[k]&&!Array.isArray(v))form.elements[k].value=v});document.getElementById('profilePhoto').textContent=initials(state.user.name);document.getElementById('profileDisplayName').textContent=state.user.name;document.getElementById('profileDisplayRole').textContent=state.user.role;document.querySelectorAll('.chip-picker').forEach(box=>{const field=box.dataset.field;box.innerHTML=TAGS[field].map(t=>`<button type="button" class="choice-chip ${state.user[field].includes(t)?'selected':''}" data-tag="${t}">${t}</button>`).join('');box.addEventListener('click',e=>{const btn=e.target.closest('.choice-chip');if(!btn)return;const arr=state.user[field];const t=btn.dataset.tag;if(arr.includes(t)) state.user[field]=arr.filter(x=>x!==t); else if(arr.length<5||field==='goals'||field==='projects') state.user[field]=[...arr,t]; else return notify('Puedes seleccionar máximo 5 opciones');btn.classList.toggle('selected');});});const slots=['Lunes 20:00','Martes 20:00','Miércoles 20:00','Jueves 20:00','Viernes 20:30','Sábado 10:00'];document.getElementById('availability').innerHTML=slots.map(t=>`<button type="button" class="choice-chip ${state.user.availability.includes(t)?'selected':''}" data-slot="${t}">${t}</button>`).join('');document.getElementById('availability').onclick=e=>{const b=e.target.closest('[data-slot]');if(!b)return;const t=b.dataset.slot;state.user.availability=state.user.availability.includes(t)?state.user.availability.filter(x=>x!==t):[...state.user.availability,t];b.classList.toggle('selected')};document.getElementById('saveProfileBtn').onclick=()=>{const data=new FormData(form);['name','city','company','role','specialty'].forEach(k=>state.user[k]=data.get(k));state.user.experience=Number(data.get('experience'));saveState();state.score+=10;saveState();notify('Perfil guardado. +10 puntos');renderProfile();};}
function renderMatching(){app.replaceChildren(cloneTpl('matchingTpl'));const members=selectRoomMembers();const avg=Math.round(members.reduce((s,p)=>s+p.calculated,0)/members.length);document.getElementById('synergyScore').textContent=avg+'%';document.getElementById('matchReasons').innerHTML=[`Aprender: ${state.user.learning.slice(0,2).join(' y ')}`,`Aportar: ${state.user.skills.slice(0,2).join(' y ')}`,`Objetivo: ${state.user.goals[0]||'Networking'}`,`Disponibilidad compartida`].map(x=>`<span>✓ ${x}</span>`).join('');document.getElementById('matchPeople').innerHTML=members.map(p=>personCard(p,false)).join('');document.getElementById('recalculateBtn').onclick=()=>{professionals.sort(()=>Math.random()-.5);notify('El algoritmo recalculó la mesa');renderMatching();};}
function renderRooms(){app.replaceChildren(cloneTpl('roomsTpl'));const members=selectRoomMembers();document.getElementById('roomRoster').innerHTML=members.map(p=>`<div class="roster-person"><div class="person-avatar">${p.initials}</div><strong>${p.name}</strong><p>${p.specialty}</p><small>Sinergia ${p.calculated}%</small></div>`).join('');document.getElementById('connectList').innerHTML=members.map(p=>`<label class="connect-choice"><input type="checkbox" value="${p.id}" ${state.connections.includes(p.id)?'checked':''}><div><strong>${p.name}</strong><small>${p.specialty}</small></div></label>`).join('');document.getElementById('joinRoomBtn').onclick=()=>{state.score+=20;saveState();notify('Sala de demostración iniciada. +20 puntos');};document.getElementById('saveConnectionsBtn').onclick=()=>{const ids=[...document.querySelectorAll('#connectList input:checked')].map(x=>Number(x.value));const added=ids.filter(id=>!state.connections.includes(id)).length;state.connections=[...new Set([...state.connections,...ids])];state.score+=added*40;saveState();notify(`${added} nuevas conexiones guardadas`);renderRooms();};startCountdown();}
function startCountdown(){let secs=5076;const el=document.getElementById('countdown');const timer=setInterval(()=>{if(!document.body.contains(el)){clearInterval(timer);return}secs--;const h=String(Math.floor(secs/3600)).padStart(2,'0'),m=String(Math.floor((secs%3600)/60)).padStart(2,'0'),s=String(secs%60).padStart(2,'0');el.textContent=`${h}:${m}:${s}`},1000)}
function renderDirectory(){app.replaceChildren(cloneTpl('directoryTpl'));const specialty=[...new Set(professionals.map(p=>p.specialty))],cities=[...new Set(professionals.map(p=>p.city))];document.getElementById('specialtyFilter').innerHTML+=""+specialty.map(x=>`<option>${x}</option>`).join('');document.getElementById('cityFilter').innerHTML+=""+cities.map(x=>`<option>${x}</option>`).join('');const update=()=>{const q=document.getElementById('directorySearch').value.toLowerCase(),s=document.getElementById('specialtyFilter').value,c=document.getElementById('cityFilter').value;const list=professionals.filter(p=>(!q||JSON.stringify(p).toLowerCase().includes(q))&&(!s||p.specialty===s)&&(!c||p.city===c));document.getElementById('directoryGrid').innerHTML=list.map(personCard).join('')||'<div class="panel">No se encontraron perfiles.</div>'};['directorySearch','specialtyFilter','cityFilter'].forEach(id=>document.getElementById(id).addEventListener('input',update));update();}
function renderNetwork(){app.replaceChildren(cloneTpl('networkTpl'));const list=professionals.filter(p=>state.connections.includes(p.id));document.getElementById('networkGrid').innerHTML=list.length?list.map(personCard).join(''):'<article class="panel"><h2>Aún no tienes conexiones</h2><p>Participa en una Mesa Estratégica para comenzar tu red.</p><button class="primary-btn" data-route="matching">Buscar mesa</button></article>';}
function renderOpportunities(){app.replaceChildren(cloneTpl('opportunitiesTpl'));const types=['Todos','Vacante','Proyecto','Consultoría','Evento','Investigación'];document.getElementById('opportunityTabs').innerHTML=types.map(t=>`<button class="tab-btn ${state.selectedOpportunityType===t?'active':''}" data-type="${t}">${t}</button>`).join('');const update=()=>{const list=state.selectedOpportunityType==='Todos'?opportunities:opportunities.filter(o=>o.type===state.selectedOpportunityType);document.getElementById('opportunityList').innerHTML=list.map(o=>`<article class="opportunity-row"><div class="op-type">${o.type==='Vacante'?'💼':o.type==='Evento'?'📅':o.type==='Investigación'?'🔬':'🏗️'}</div><div><span class="pill">${o.type}</span><h3>${o.title}</h3><p>${o.description}</p><small>📍 ${o.location} · Publicado por ${o.author}</small></div><button class="secondary-btn" onclick="notify('Interés registrado en ${o.title}')">Me interesa</button></article>`).join('')};document.getElementById('opportunityTabs').onclick=e=>{const b=e.target.closest('[data-type]');if(!b)return;state.selectedOpportunityType=b.dataset.type;renderOpportunities()};document.getElementById('newOpportunityBtn').onclick=()=>document.getElementById('opportunityDialog').showModal();update();}
function renderHistory(){app.replaceChildren(cloneTpl('historyTpl'));document.getElementById('historyTimeline').innerHTML=history.map(h=>`<article class="timeline-item"><div class="timeline-dot">✓</div><div class="timeline-card"><span class="pill">${h.date}</span><h3>${h.title}</h3><p><strong>Participantes:</strong> ${h.participants.join(', ')}</p><p><strong>Conexiones creadas:</strong> ${h.connections}</p><p><strong>Nota:</strong> ${h.note}</p></div></article>`).join('');}
function renderScore(){app.replaceChildren(cloneTpl('scoreTpl'));document.getElementById('scoreValue').textContent=state.score;document.getElementById('scoreActivity').innerHTML=activities.map(a=>`<div class="activity-item"><span class="activity-icon">${a.icon}</span><div><p>${a.text}</p><small>${a.time}</small></div><strong>${a.icon==='🏆'?'+20':''}</strong></div>`).join('');}
function renderNotifications(){app.replaceChildren(cloneTpl('notificationsTpl'));document.getElementById('notificationsList').innerHTML=activities.map(a=>`<div class="activity-item"><span class="activity-icon">${a.icon}</span><div><p>${a.text}</p><small>${a.time}</small></div></div>`).join('');}
function bindRouteButtons(){document.querySelectorAll('[data-route]').forEach(b=>{b.onclick=()=>setRoute(b.dataset.route);b.onkeydown=e=>{if(e.key==='Enter')setRoute(b.dataset.route)}})}

const authHost=document.getElementById('authHost');
const onboardingHost=document.getElementById('onboardingHost');
function setAppVisible(show){['.topbar','.app-shell','.bottom-nav'].forEach(sel=>document.querySelector(sel)?.classList.toggle('app-hidden',!show));}
function authError(msg){const e=document.getElementById('authError');if(e){e.textContent=msg;e.classList.add('show')}}
function passwordField(name,label,confirm=false){return `<label>${label}<div class="password-wrap"><input type="password" name="${name}" minlength="4" required autocomplete="${confirm?'new-password':'current-password'}"><button type="button" class="password-toggle" aria-label="Mostrar contraseña">👁</button></div></label>`}
function bindPasswordToggles(root){root.querySelectorAll('.password-toggle').forEach(b=>b.onclick=()=>{const i=b.parentElement.querySelector('input');i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'👁':'🙈'})}
function showAuth(mode='login'){
  setAppVisible(false); onboardingHost.innerHTML='';
  authHost.innerHTML=`<div class="auth-layer"><section class="auth-phone"><div class="auth-hero"><div class="auth-logo">CN</div><h1>ConstructNet UTP</h1><p>Construyendo conexiones que construyen proyectos.</p></div><div class="auth-body"><div class="auth-tabs"><button class="auth-tab ${mode==='login'?'active':''}" data-auth-tab="login">Ingresar</button><button class="auth-tab ${mode==='register'?'active':''}" data-auth-tab="register">Crear cuenta</button></div>${mode==='login'?`<form id="loginForm" class="auth-form"><h2>Bienvenido</h2><p>Ingresa para continuar con tu red profesional.</p><label>Correo electrónico<input type="email" name="email" required autocomplete="email" placeholder="nombre@correo.com"></label>${passwordField('password','Contraseña')}<div id="authError" class="auth-error"></div><button class="primary-btn full" type="submit">Iniciar sesión</button><div class="auth-note">Prototipo académico: las cuentas se guardan localmente en este navegador.</div></form>`:`<form id="registerForm" class="auth-form"><h2>Crea tu cuenta</h2><p>Luego completarás tu ADN Profesional paso a paso.</p><label>Nombres y apellidos<input name="name" required placeholder="Ej. Ana Torres"></label><label>Correo electrónico<input type="email" name="email" required autocomplete="email" placeholder="nombre@correo.com"></label>${passwordField('password','Contraseña',true)}${passwordField('confirm','Confirmar contraseña',true)}<div id="authError" class="auth-error"></div><button class="primary-btn full" type="submit">Crear cuenta</button><div class="auth-note">Para una versión pública multiusuario real se puede conectar posteriormente a Firebase o Supabase.</div></form>`}</div></section></div>`;
  authHost.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>showAuth(b.dataset.authTab));bindPasswordToggles(authHost);
  const login=document.getElementById('loginForm');if(login)login.onsubmit=e=>{e.preventDefault();const d=new FormData(login),email=String(d.get('email')).trim().toLowerCase(),pass=String(d.get('password'));const a=getAccounts().find(x=>x.email===email);if(!a||a.password!==pass)return authError('Correo o contraseña incorrectos.');loadAccount(email);authHost.innerHTML='';if(state.profileCompleted){setAppVisible(true);render()}else showOnboarding(1)};
  const reg=document.getElementById('registerForm');if(reg)reg.onsubmit=e=>{e.preventDefault();const d=new FormData(reg),name=String(d.get('name')).trim(),email=String(d.get('email')).trim().toLowerCase(),pass=String(d.get('password')),conf=String(d.get('confirm'));if(pass!==conf)return authError('Las contraseñas no coinciden.');if(getAccounts().some(x=>x.email===email))return authError('Ese correo ya tiene una cuenta.');const accounts=getAccounts();accounts.push({email,password:pass,user:{...defaultUser,name},connections:[],score:10,profileCompleted:false});putAccounts(accounts);loadAccount(email);authHost.innerHTML='';showOnboarding(1)};
}
function chipHtml(items,selected=[],field=''){return `<div class="wizard-chips" data-wizard-field="${field}">${items.map(x=>`<button type="button" class="wizard-chip ${selected.includes(x)?'selected':''}" data-value="${x}">${x}</button>`).join('')}</div>`}
function bindWizardChips(root,field,max=5){root.querySelectorAll(`[data-wizard-field="${field}"] .wizard-chip`).forEach(b=>b.onclick=()=>{const arr=state.user[field]||[],v=b.dataset.value;if(arr.includes(v)){state.user[field]=arr.filter(x=>x!==v);b.classList.remove('selected')}else if(arr.length<max){state.user[field]=[...arr,v];b.classList.add('selected')}else notify(`Máximo ${max} opciones`);})}
function showOnboarding(step=1){
  setAppVisible(false);authHost.innerHTML='';const total=6,pct=Math.round(step/total*100);let body='';
  if(step===1)body=`<h1>Cuéntanos quién eres</h1><p>Esta información será visible en tu perfil profesional.</p><div class="wizard-grid"><label>Nombre completo<input id="obName" value="${state.user.name||''}" required></label><label>Ciudad<input id="obCity" value="${state.user.city||''}" placeholder="Ej. Chiclayo"></label><label>Empresa / entidad<input id="obCompany" value="${state.user.company||''}" placeholder="Ej. Constructora Norte"></label><label>Cargo<input id="obRole" value="${state.user.role||''}" placeholder="Ej. Ingeniero de Calidad"></label><label>Especialidad<select id="obSpecialty"><option>Gestión de proyectos</option><option>Gestión pública</option><option>BIM</option><option>Calidad</option><option>Costos</option><option>Planeamiento</option><option>Residencia de obra</option><option>Seguridad / SSOMA</option></select></label><label>Años de experiencia<input id="obExperience" type="number" min="0" value="${state.user.experience||0}"></label></div>`;
  if(step===2)body=`<h1>Tu valor profesional</h1><p>Selecciona hasta 5 conocimientos que dominas. Esto ayuda a saber qué puedes aportar a una Mesa Estratégica.</p><div class="wizard-section"><h3>Lo que domino</h3>${chipHtml(TAGS.skills,state.user.skills,'skills')}</div>`;
  if(step===3)body=`<h1>¿Qué quieres aprender?</h1><p>Selecciona hasta 5 temas. El motor buscará profesionales que puedan aportarte valor.</p><div class="wizard-section">${chipHtml(TAGS.learning,state.user.learning,'learning')}</div><div class="wizard-section"><h3>¿Qué puedes aportar además?</h3><p>Mentoría, contactos, experiencia u otro apoyo profesional.</p>${chipHtml(TAGS.offers,state.user.offers,'offers')}</div>`;
  if(step===4)body=`<h1>¿Qué estás buscando?</h1><p>Esto permite formar mesas con objetivos compatibles.</p><div class="wizard-section"><h3>Objetivos profesionales</h3>${chipHtml(TAGS.goals,state.user.goals,'goals')}</div><div class="wizard-section"><h3>Tipos de proyecto</h3>${chipHtml(TAGS.projects,state.user.projects,'projects')}</div>`;
  if(step===5){const slots=['Lunes 20:00','Martes 20:00','Miércoles 20:00','Jueves 20:00','Viernes 20:30','Sábado 10:00'];body=`<h1>Disponibilidad</h1><p>Selecciona los horarios en los que normalmente podrías participar en una Mesa Estratégica.</p><div class="wizard-section">${chipHtml(slots,state.user.availability,'availability')}</div><div class="auth-note">Las mesas se forman con mínimo 3 y máximo 6 participantes, considerando complementariedad y disponibilidad común.</div>`}
  if(step===6){const matches=professionals.map(p=>calculateSynergy(state.user,p)).filter(x=>x>=70).length;body=`<div class="welcome-result"><div class="big-check">✓</div><h1>¡Tu ADN Profesional está listo!</h1><p>ConstructNet ya puede empezar a encontrar conexiones estratégicas para ti.</p><div class="value-preview"><div><strong>${matches||3}+</strong><span>perfiles con alta sinergia</span></div><div><strong>${state.user.learning.length}</strong><span>intereses de aprendizaje</span></div><div><strong>${state.user.skills.length}</strong><span>conocimientos que aportas</span></div><div><strong>3–6</strong><span>personas por mesa</span></div></div><div class="reason-box"><strong>¿Qué hará el motor?</strong><p>Buscará complementariedad entre lo que quieres aprender, lo que otros dominan, objetivos profesionales, proyectos y horarios disponibles.</p></div></div>`}
  onboardingHost.innerHTML=`<div class="onboarding-layer"><section class="onboarding-phone"><div class="onboarding-head"><div class="auth-logo">CN</div><div><strong>Construye tu ADN Profesional</strong><small>Paso ${step} de ${total}</small></div></div><div class="onboarding-progress"><i style="width:${pct}%"></i></div><div class="onboarding-body">${body}</div><div class="onboarding-actions">${step>1&&step<6?'<button id="obBack" class="secondary-btn">Atrás</button>':''}<button id="obNext" class="primary-btn">${step===6?'Comenzar mi networking':'Continuar'}</button></div></section></div>`;
  if(step===1){document.getElementById('obSpecialty').value=state.user.specialty;}
  ['skills','learning','offers','goals','projects','availability'].forEach(f=>{if(onboardingHost.querySelector(`[data-wizard-field="${f}"]`))bindWizardChips(onboardingHost,f,f==='availability'?6:(f==='goals'||f==='projects'?10:5))});
  document.getElementById('obBack')?.addEventListener('click',()=>showOnboarding(step-1));
  document.getElementById('obNext').onclick=()=>{if(step===1){state.user.name=document.getElementById('obName').value.trim();state.user.city=document.getElementById('obCity').value.trim();state.user.company=document.getElementById('obCompany').value.trim();state.user.role=document.getElementById('obRole').value.trim();state.user.specialty=document.getElementById('obSpecialty').value;state.user.experience=Number(document.getElementById('obExperience').value||0);if(!state.user.name)return notify('Ingresa tu nombre completo');}if(step<6){persistAccount();showOnboarding(step+1)}else{state.profileCompleted=true;state.score=Math.max(state.score,10);persistAccount();onboardingHost.innerHTML='';setAppVisible(true);render();notify('¡Bienvenido a ConstructNet UTP!')}};
}
function logout(){currentEmail='';localStorage.removeItem(SESSION_KEY);state={route:'dashboard',user:{...defaultUser},connections:[],score:0,selectedOpportunityType:'Todos',profileCompleted:false};showAuth('login')}
function render(){const map={dashboard:renderDashboard,profile:renderProfile,matching:renderMatching,rooms:renderRooms,directory:renderDirectory,network:renderNetwork,opportunities:renderOpportunities,history:renderHistory,score:renderScore,notifications:renderNotifications};(map[state.route]||renderDashboard)();bindRouteButtons();document.querySelectorAll('.nav-item,.bottom-item').forEach(n=>n.classList.toggle('active',n.dataset.route===state.route));app.focus({preventScroll:true});}

document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('logoutBtn').onclick=logout;
document.getElementById('opportunityForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return; e.preventDefault();const d=new FormData(e.currentTarget);opportunities.unshift({id:Date.now(),type:d.get('type'),title:d.get('title'),description:d.get('description'),location:d.get('location')||'Virtual',author:state.user.name});state.score+=15;saveState();document.getElementById('opportunityDialog').close();notify('Oportunidad publicada. +15 puntos');renderOpportunities();e.currentTarget.reset();});
if(currentEmail&&loadAccount(currentEmail)){if(state.profileCompleted){setAppVisible(true);render()}else showOnboarding(1)}else showAuth('login');
