-- Ejecutar en Supabase > SQL Editor SOLO si deseas pruebas multiusuario entre dispositivos.
create table if not exists profiles (
  email text primary key,
  name text,
  phone text,
  city text,
  company text,
  role text,
  sector text,
  specialty text,
  experience int default 0,
  bio text,
  linkedin text,
  avatar text,
  skills jsonb default '[]'::jsonb,
  learning jsonb default '[]'::jsonb,
  offers jsonb default '[]'::jsonb,
  goals jsonb default '[]'::jsonb,
  projects jsonb default '[]'::jsonb,
  availability jsonb default '[]'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists topic_members (
  id bigint generated by default as identity primary key,
  topic_id text not null,
  email text not null,
  joined_at timestamptz default now(),
  unique(topic_id,email)
);

create table if not exists opportunities (
  id bigint generated by default as identity primary key,
  author_email text,
  author_name text,
  type text,
  title text,
  description text,
  location text,
  created_at timestamptz default now()
);

alter table profiles enable row level security;
alter table topic_members enable row level security;
alter table opportunities enable row level security;

-- Políticas abiertas SOLO para un prototipo académico.
create policy "prototype_profiles_read" on profiles for select using (true);
create policy "prototype_profiles_write" on profiles for all using (true) with check (true);
create policy "prototype_topics_read" on topic_members for select using (true);
create policy "prototype_topics_write" on topic_members for all using (true) with check (true);
create policy "prototype_opps_read" on opportunities for select using (true);
create policy "prototype_opps_write" on opportunities for all using (true) with check (true);
